### ISSUE TITLE
About dataset： extend the historical traffic flow data

### ISSUE THREAD

**Issue by quduoduo** [Guoxs/xTP-LLM#1]
Dear Guo, thank you for your outstanding work. I’m wondering how I could extend the historical traffic flow data to cover the past month or even the past year. Any guidance would be greatly appreciated. Thank you!

**Comment by Guoxs** [comment]
Hello, I think you need to rebuild the dataset from scratch. As we state in our paper, our traffic data comes from LargeST dataset (https://github.com/liuxu77/LargeST) , our PoIs data is obtained through OpenStreetMap, and the weather data is collected from the National Oceanic and Atmospheric Administration (NOAA3). You can use these raw data to build your own dataset.
